version: '3.8'

services:

  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/page_flow
      SPRING_DATASOURCE_USERNAME: yaroslav
      SPRING_DATASOURCE_PASSWORD: test
      TOKEN: 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

  db:
    image: postgres
    environment:
      POSTGRES_DB: page_flow
      POSTGRES_USER: yaroslav
      POSTGRES_PASSWORD: test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
      interval: 10s
      timeout: 15s
      retries: 3

volumes:
  db-data:
